Add option delete
kingscode/vuetify-file-manager pull request #4
Opened 2019-12-19 11:41 UTC by martn001

2019-12-19 12:10 UTC, Deluze requested changes

2019-12-19 12:10 UTC, Deluze commented on src/FileManager/ContextMenu.vue
> +                <v-card-title class="headline">Bevestiging voor het verwijderen</v-card-title>
This is a package. Use the built-in i18n version in Vuetify for these string literals.

2019-12-19 12:10 UTC, Deluze commented on src/FileManager/ContextMenu.vue
> +                        Annuleren
Translation here too

2019-12-19 12:10 UTC, Deluze commented on src/FileManager/ContextMenu.vue
> +                        Verwijderen
Translation here too

2019-12-19 12:10 UTC, Deluze commented on src/FileManager/ContextMenu.vue
> +</style>
```suggestion
</style>

```

2019-12-19 12:10 UTC, Deluze commented on src/FileManager/FolderView.vue
> +            @rightMouseClicked="showContextMenu"/>
fix the alignment here

2019-12-19 12:10 UTC, Deluze commented on src/FileManager/FolderView.vue
> +            if (typeof this.deleteImage === 'function') {
All you have to do here is check for the deleteImage to be falsy. Since the prop type should already be a Function.

2019-12-19 12:10 UTC, Deluze commented on src/FileManager/Folders.vue
> +            context="Folder verwijderen"
Add translations

2019-12-23 09:04 UTC, martn001 commented on src/FileManager/ContextMenu.vue
> +                <v-card-title class="headline">Bevestiging voor het verwijderen</v-card-title>
@Deluze Ik weet niet of het de bedoeling is dat deze package de uitbreiding nodig heeft voor een vertaling. Dit was eerder ook al niet toegepast aan de package. Mocht er een vertaling nodig zijn, dan moet @ricardovanlaarhoven er ook mee akkoord gaan. Heb je dit met hem overlegd?

2019-12-23 11:46 UTC, Deluze approved these changes

2019-12-23 11:48 UTC, Deluze commented on src/FileManager/ContextMenu.vue
> +                <v-card-title class="headline">Bevestiging voor het verwijderen</v-card-title>
Nope. En het is ook geen uitbreiding. Er zit gewoon i18n al in Vuetify zelf. Elke package van Vuetify maakt daar gebruik van

2019-12-23 16:11 UTC, merged